DROP TABLE EMPLEADOS;
DROP TABLE TRAMO_DESCTO_SINDICATO;
DROP TABLE TRAMO_ASIG_JEFE;
DROP TABLE HABER_CALC_SALARIO;
DROP TABLE ERROR_PROCESO;

CREATE TABLE EMPLEADOS
AS SELECT * FROM employees;

CREATE TABLE TRAMO_ASIG_JEFE
(tramo_inf_aj NUMBER(2) NOT NULL,
 tramo_sup_aj NUMBER(2) NOT NULL,
 porc_asig_jefe NUMBER(2) NOT NULL,
 CONSTRAINT PK_TRAMO_ASIG_JEFE PRIMARY KEY(tramo_inf_aj,tramo_sup_aj));

 CREATE TABLE tramo_descto_sindicato
(nro_tramo_ds  NUMBER(2) NOT NULL,
 tramo_inf_ds NUMBER(8) NOT NULL,
 tramo_sup_ds NUMBER(8) NOT NULL,
 porc_ds NUMBER(4,3) NOT NULL,
CONSTRAINT PK_TRAMO_DESCTO_JEFE PRIMARY KEY(nro_tramo_ds));


 CREATE TABLE HABER_CALC_SALARIO
 (id_empleado NUMBER(3) NOT NULL,
  anno_mes_proc NUMBER(6) NOT NULL,
  valor_sldo_base NUMBER(8) NOT NULL,
  valor_comision NUMBER(5) NOT NULL,
  valor_comision_jefe NUMBER(5) NOT NULL,
  valor_colacion NUMBER(5) NOT NULL,
  valor_movil NUMBER(8) NOT NULL,
  valor_descto_sindicato NUMBER(8) NOT NULL,
  valor_alc_liquido NUMBER(8) NOT NULL,
  CONSTRAINT PK_HABER_CAL_SALARIO PRIMARY KEY(id_empleado,anno_mes_proc));

CREATE TABLE ERROR_PROCESO
(sec_error NUMBER(3) NOT NULL,
 rutina_error VARCHAR2(100) NOT NULL,
 mensaje_error VARCHAR2(250) NOT NULL,
 CONSTRAINT PK_ERROR_PROCESO PRIMARY KEY(sec_error));
 
INSERT INTO TRAMO_ASIG_JEFE VALUES(1,5,5);
INSERT INTO TRAMO_ASIG_JEFE VALUES(5,7,5);
INSERT INTO TRAMO_ASIG_JEFE VALUES(8,10,7);
INSERT INTO TRAMO_ASIG_JEFE VALUES(11,15,9);
INSERT INTO TRAMO_ASIG_JEFE VALUES(16,20,10);

INSERT INTO tramo_descto_sindicato VALUES(1,1000,3000,0.02);
INSERT INTO tramo_descto_sindicato VALUES(2,3001,6000,0.025);
INSERT INTO tramo_descto_sindicato VALUES(3,8000,10000,0.035);
INSERT INTO tramo_descto_sindicato VALUES(4,10001,30000,0.045);
COMMIT;
