# Generated by Django 4.2.1 on 2023-05-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('HG', 'Hongo Gourmet'), ('EM', 'Espora Magico')], max_length=2)),
                ('prod_imagen', models.ImageField(upload_to='producto')),
            ],
        ),
    ]
