# Generated by Django 4.2.1 on 2023-05-30 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginaV3_app', '0002_alter_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('HG', 'Hongos Gourmet'), ('EM', 'Esporas Psilocybes')], max_length=2),
        ),
    ]
